// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ARMotionCam",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "ARMotionCam",
            targets: ["AppModule"],
            bundleIdentifier: "com.Lia316.ARMotionCam",
            teamIdentifier: "T79FMP6Q2L",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .camera),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .fileAccess(.userSelectedFiles, mode: .readOnly),
                .camera(purposeString: "This app uses the camera to overlay virtual objects in the real world.")
            ],
            appCategory: .photography
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)